version: '3.8'

services:
  # База данных MongoDB
  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - vpn-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securePassword123
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Бэкенд-сервер (API)
  server:
    build:
      context: ./server
    container_name: server
    hostname: server
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:securePassword123@mongodb:27017/vpn-service?authSource=admin
      - JWT_SECRET=secure_secret_key_production_vpn_2025
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=*
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
      - LOGS_DIR=logs
      - CONFIGS_UPLOAD_PATH=uploads/configs
    volumes:
      - server_logs:/app/logs
      - server_uploads:/app/uploads
    ports:
      - "3000:3000"
    networks:
      - vpn-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Админ-панель (фронтенд)
  admin:
    build:
      context: ./admin-panel
    container_name: admin
    restart: always
    depends_on:
      - server
    volumes:
      - admin_logs:/var/log/nginx
    ports:
      - "3001:3001"
    networks:
      - vpn-network
    links:
      - server:server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  vpn-network:
    driver: bridge

volumes:
  mongodb_data:
  server_logs:
  server_uploads:
  admin_logs: