version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vpn-network

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vpn-service
      - JWT_SECRET=vpn-super-secret-key-change-in-production
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - vpn-network

  admin-panel:
    build: ./admin-panel
    ports:
      - "3001:80"
    depends_on:
      - server
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge

volumes:
  mongodb_data: 